### ISSUE TITLE
WETH is not shown

### ISSUE THREAD

**Issue by DonnyPerni** [luzzif/folio#7]
With this check you remove all Wrapped Ethereum tokens because the coingecko API returns `0.0` as `circulatingSupply`

Here the check: https://github.com/luzzif/folio/blob/4be0000ed403434a66e25c8fc64afcda36367a01/src/utils/index.js#L76

Here the API: https://api.coingecko.com/api/v3/coins/weth?localization=false&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false

**Comment by luzzif** [comment]
First of all, thanks for your contribution to the project. The check is probably obsolete as of now. Going to have a look at it asap.

**Comment by guerrap** [comment]
Fixed in https://github.com/luzzif/folio/pull/6
